version: '3'

services:
  # Test Runner Service
  test-runner:
    build: .
    environment:
      # Connect to Appium running on the HOST machine
      - APPIUM_HOST=host.docker.internal
      - APPIUM_PORT=4723
      - APPIUM_PATH=/wd/hub

      # Device Configurations (from Jenkins/Host)
      - DEVICE_NAME=Pixel_9_pro
      - PLATFORM_VERSION=15

      # App Path (must be absolute path on HOST for Appium to find it)
      - APP_PATH=/Users/apple/Desktop/wdio-appium-bdd/apps/android/app-workq-release-8.apk

      # Credentials & Config passed from Host/Jenkins
      - TAG_EXPRESSION
      - TEST_EMAIL
      - TEST_PASSWORD
      - BUGASURA_API_KEY
    volumes:
      - ./allure-results:/app/allure-results
      - ./reports:/app/reports
    # Command to run tests
    command: npm run android
